apiVersion: v1
kind: Service
metadata:
  name: frontoffice-be-svc
  namespace: partner
  labels:
    app: frontoffice-be
    service: frontoffice-be-svc
spec:
  ports:
  - port: 3002
    targetPort: 3002
    name: tcp
  selector:
    app: frontoffice-be
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: partner-ksa
  namespace: partner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontoffice-be
  namespace: partner
  labels:
    app: frontoffice-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontoffice-be
  template:
    metadata:
      labels:
        app: frontoffice-be
    spec:
      serviceAccountName: partner-ksa
      containers:
      - name: frontoffice-be
        image: asia.gcr.io/aif-staging/frontoffice-be
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: PS_APP_ENV
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_APP_ENV
          - name: PS_APP_PORT
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_APP_PORT
          - name: PS_SLACK_TOKEN
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_SLACK_TOKEN
          - name: PS_SLACK_CHANNEL
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_SLACK_CHANNEL
          - name: PS_PG_HOST
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG_HOST
          - name: PS_PG_PORT
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG_PORT
          - name: PS_PG_USER
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: PS_PG_USER
          - name: PS_PG_PASS
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: PS_PG_PASS
          - name: PS_PG_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG_DB_NAME
          - name: PS_PG2_HOST
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG2_HOST
          - name: PS_PG2_PORT
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG2_PORT
          - name: PS_PG2_USER
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: PS_PG2_USER
          - name: PS_PG2_PASS
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: PS_PG2_PASS
          - name: PS_PG2_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_PG2_DB_NAME
          - name: PS_GCP_CLOUD_SQL
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: PS_GCP_CLOUD_SQL
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontoffice-be-hpa
  namespace: partner
  labels:
    app: frontoffice-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontoffice-be
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80