apiVersion: v1
kind: Service
metadata:
  name: frontoffice-be-svc
  namespace: frontoffice
  labels:
    app: frontoffice-be
    service: frontoffice-be-svc
spec:
  ports:
  - port: 3001
    targetPort: 3001
    name: tcp
  selector:
    app: frontoffice-be
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontoffice-ksa
  namespace: frontoffice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontoffice-be
  namespace: frontoffice
  labels:
    app: frontoffice-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontoffice-be
  template:
    metadata:
      labels:
        app: frontoffice-be
    spec:
      serviceAccountName: frontoffice-ksa
      containers:
      - name: frontoffice-be
        image: asia.gcr.io/aif-staging/frontoffice-be
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: APP_ENV
          - name: BASE_URL
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: BASE_URL
          - name: CLOUD_PROVIDER
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: CLOUD_PROVIDER
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: APP_PORT
          - name: SLACK_TOKEN
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: SLACK_TOKEN
          - name: SLACK_CHANNEL
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: SLACK_CHANNEL
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: DB_NAME
          - name: MAILJET_EMAIL
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: MAILJET_EMAIL
          - name: MAILJET_USERNAME
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: MAILJET_USERNAME
          - name: MAILJET_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: MAILJET_PUBLIC_KEY
          - name: MAILJET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: frontoffice-be-secret
                key: MAILJET_SECRET_KEY
          - name: JWT_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: JWT_SECRET_KEY
          - name: JWT_EXPIRES_MINUTES
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: JWT_EXPIRES_MINUTES
          - name: JWT_RESET_PASSWORD_EXPIRES_MINUTES
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: JWT_RESET_PASSWORD_EXPIRES_MINUTES
          - name: JWT_EMAIL_VERIFICATION_EXPIRES_MINUTES
            valueFrom:
              configMapKeyRef:
                name: frontoffice-be-config
                key: JWT_EMAIL_VERIFICATION_EXPIRES_MINUTES
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontoffice-be-hpa
  namespace: frontoffice
  labels:
    app: frontoffice-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontoffice-be
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80