name: Build
on:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, dev]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run tests with coverage
        run: go test -v ./... -coverprofile=coverage.out

      - name: Install gcov2lcov
        run: go install github.com/jandelgado/gcov2lcov@latest

      - name: Convert coverage to lcov
        run: $HOME/go/bin/gcov2lcov coverage.out > coverage.lcov

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Aif-ScoreEzy_frontoffice
            -Dsonar.organization=aif-scoreezy
            -Dsonar.go.coverage.reportPaths=coverage.lcov
