name: Build
on:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, dev]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run tests with coverage
        run: go test -v ./... -coverprofile=coverage.out

      - name: Debug coverage file
        run: cat coverage.out

      - name: Install gcov2lcov
        run: go install github.com/jandelgado/gcov2lcov@latest

      - name: Convert coverage to lcov
        run: $HOME/go/bin/gcov2lcov -infile coverage.out -outfile coverage.lcov

      - name: Show lcov output
        run: cat coverage.lcov

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Aif-ScoreEzy_frontoffice
            -Dsonar.organization=aif-scoreezy
            -Dsonar.go.coverage.reportPaths=coverage.lcov
            -Dsonar.sources=.
            -Dsonar.sources=internal,pkg
            -Dsonar.verbose=true
